# Generated by Django 6.0.7 on 2026-07-12 08:10

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_vehicle_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["make", "model"]},
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="category",
            field=models.CharField(
                choices=[
                    ("SUV", "SUV"),
                    ("Sedan", "Sedan"),
                    ("Hatchback", "Hatchback"),
                    ("Truck", "Truck"),
                    ("Luxury", "Luxury"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
